export const COLORS = {
  // Dark theme
  dark: {
    background: '#000000',
    surface: '#121212',
    surfaceLight: '#1E1E1E',
    surfaceElevated: '#252525',
    primary: '#E040FB',
    primaryGradientEnd: '#536DFE',
    secondary: '#536DFE',
    accent: '#00E5FF',
    text: '#FFFFFF',
    textSecondary: '#A0A0A0',
    textTertiary: '#666666',
    danger: '#FF4757',
    success: '#2ED573',
    warning: '#FFA502',
    heart: '#FF4757',
    border: '#2A2A2A',
    borderLight: '#1A1A1A',
    inputBg: '#1E1E1E',
    overlay: 'rgba(0,0,0,0.7)',
    tabBar: '#0A0A0A',
    card: '#121212',
    skeleton: '#1E1E1E',
    skeletonHighlight: '#2A2A2A',
  },
  // Light theme
  light: {
    background: '#FAFAFA',
    surface: '#FFFFFF',
    surfaceLight: '#F5F5F5',
    surfaceElevated: '#FFFFFF',
    primary: '#E040FB',
    primaryGradientEnd: '#536DFE',
    secondary: '#536DFE',
    accent: '#00B0FF',
    text: '#262626',
    textSecondary: '#737373',
    textTertiary: '#999999',
    danger: '#FF4757',
    success: '#2ED573',
    warning: '#FFA502',
    heart: '#FF4757',
    border: '#DBDBDB',
    borderLight: '#EFEFEF',
    inputBg: '#F5F5F5',
    overlay: 'rgba(0,0,0,0.5)',
    tabBar: '#FFFFFF',
    card: '#FFFFFF',
    skeleton: '#EFEFEF',
    skeletonHighlight: '#F5F5F5',
  }
};

export const FONTS = {
  regular: { fontSize: 14, fontWeight: '400' },
  medium: { fontSize: 14, fontWeight: '500' },
  semibold: { fontSize: 14, fontWeight: '600' },
  bold: { fontSize: 14, fontWeight: '700' },
  title: { fontSize: 24, fontWeight: '700' },
  subtitle: { fontSize: 18, fontWeight: '600' },
  caption: { fontSize: 12, fontWeight: '400' },
  small: { fontSize: 11, fontWeight: '400' },
};

export const SIZES = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  borderRadius: 12,
  borderRadiusSm: 8,
  borderRadiusLg: 20,
  borderRadiusFull: 999,
  avatar: 40,
  avatarSmall: 32,
  avatarLarge: 80,
  avatarXLarge: 120,
  tabBarHeight: 60,
  headerHeight: 56,
  inputHeight: 48,
  buttonHeight: 48,
  storyCircle: 68,
  storyCircleSmall: 56,
  postImageHeight: 400,
};

export const SHADOWS = {
  small: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  medium: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  large: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
};

export default { COLORS, FONTS, SIZES, SHADOWS };
